import { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, GuildMember } from 'discord.js';
import prisma from '../lib/prisma';
import { CONFIG } from '../config';
import { isStaff } from '../utils/permissions';
import { generateToken } from '../utils/tokenGenerator';
import { uploadFile } from '../utils/fileHost';
import { consumeStock } from '../utils/gameManager';
import { createTokenDeliveryEmbed } from '../utils/embeds';
import { logAction, logTenant } from '../utils/logging';
import { pickOwnerAccount, recordOwnerUsage } from '../utils/steampassPool';
import { pendingVerificationTimers } from '../utils/ticketManager';

export async function execute(interaction: any): Promise<void> {
  const gameName = interaction.options.getString('game')!;
  const deduct = interaction.options.getBoolean('deduct') ?? true;

  if (!isStaff(interaction.member as GuildMember)) {
    return interaction.editReply({ content: '❌ **Unauthorized:** Staff clearance required.' });
  }

  const game = await prisma.game.findUnique({ where: { name: gameName } });
  if (!game) return interaction.editReply({ content: `❌ **Not Found:** Game **${gameName}** does not exist.` });
  if (!game.appId) return interaction.editReply({ content: `❌ **No AppID:** Game **${gameName}** has no AppID configured.` });

  const startEmbed = new EmbedBuilder()
    .setTitle('⚙️ Generating Token (Staff Bypass)')
    .setDescription(`Generating a real token for **${game.name}** (AppID: \`${game.appId}\`).\n*Requested by ${interaction.user}.*\nDeduct stock: \`${deduct ? 'YES' : 'NO'}\``)
    .setColor(0x5865F2)
    .setTimestamp();
  await interaction.editReply({ embeds: [startEmbed] });

  let poolAccountId: number | null = null;
  let accountOverride: { login: string; password: string } | undefined;
  if (interaction.guildId === CONFIG.OWNER_GUILD_ID) {
    const picked = await pickOwnerAccount(game.appId);
    if (picked.exhausted) {
      return interaction.editReply({ content: `🔴 **${game.name}** is **out of tokens for today.** Fresh tokens unlock at 00:00 UTC — please try again tomorrow.` });
    }
    if (picked.account) {
      poolAccountId = picked.account.id;
      accountOverride = { login: picked.account.login, password: picked.account.password };
    }
  }

  try {
    const { zipPath, logs, installerKey, ticketHash, expectedHmac, appIdBound } = await generateToken(game.appId, game.name, interaction.guildId, accountOverride);
    console.log(`[TokenGen-Cmd] Logs for ${game.name}:\n${logs}`);
    if (poolAccountId) await recordOwnerUsage(poolAccountId, game.appId);

    if (!zipPath) {
      const failEmbed = new EmbedBuilder()
        .setTitle('⚠️ Token Generation Failed')
        .setDescription(`Could not generate token for **${game.name}**.\n\n\`\`\`\n${logs.slice(-500)}\n\`\`\``)
        .setColor(0xED4245)
        .setTimestamp();
      await interaction.editReply({ embeds: [failEmbed] });
      if (interaction.guild) {
        await logAction(interaction.guild, '⚠️ /tokengen Failed', `Staff ${interaction.user} ran /tokengen for **${game.name}** — generation failed.\n\`\`\`\n${logs.slice(-500)}\n\`\`\``, 0xED4245);
      }
      return;
    }

    if (deduct) {
      await consumeStock(game.id).catch(e => console.error('[TokenGen-Cmd] consumeStock failed:', e));
    }

    const safeGameName = game.name.replace(/[<>:"/\\|?*]/g, '').trim();
    const fsMod = await import('fs');
    const zipBytes = fsMod.statSync(zipPath).size;
    const zipMB = zipBytes / (1024 * 1024);
    const tier = interaction.guild?.premiumTier ?? 0;
    const limitMB = tier >= 3 ? 100 : tier >= 2 ? 50 : 10;

    const successFields = [
      { name: '🎮 Game', value: `\`${game.name}\``, inline: true },
      { name: '🆔 AppID', value: `\`${game.appId}\``, inline: true },
      { name: '📦 Size', value: `\`${zipMB.toFixed(1)} MB\``, inline: true },
      { name: '🛠️ Generated by', value: `${interaction.user}`, inline: true },
      { name: '💰 Stock Deducted', value: `\`${deduct ? 'YES' : 'NO'}\``, inline: true },
      { name: '📋 Method', value: '`/tokengen` (staff bypass)', inline: true },
    ];

    const ticketHere = await prisma.ticket.findFirst({
      where: { channelId: interaction.channelId, status: { in: ['OPEN', 'CLAIMED'] } }
    });
    const worksRow = new ActionRowBuilder<ButtonBuilder>().addComponents(
      new ButtonBuilder().setCustomId('works_yes').setLabel('Confirm Working').setStyle(ButtonStyle.Success),
      new ButtonBuilder().setCustomId('works_no').setLabel('Report Issue').setStyle(ButtonStyle.Danger)
    );

    const persistent = !ticketHere;

    try {
      let delivered: any;
      await interaction.editReply({ embeds: [
        new EmbedBuilder()
          .setTitle('📤 Uploading Token')
          .setDescription(`Zip is **${zipMB.toFixed(1)} MB** (Discord limit here is ${limitMB} MB). Uploading to file host...`)
          .setColor(0xFEE75C)
          .setTimestamp()
      ] });
      const upload = await uploadFile(zipPath, '72h', installerKey, { ticketHash, expectedHmac, appIdBound }, persistent);
      const hostedEmbed = createTokenDeliveryEmbed(
        game.name,
        ticketHere?.userId || interaction.user.id,
        interaction.user,
        { url: upload.url, expiryText: upload.expiryText, sizeMB: zipMB.toFixed(1) },
      ).addFields(successFields);
      delivered = await interaction.editReply({
        embeds: [hostedEmbed],
        components: ticketHere ? [worksRow] : []
      });

      if (ticketHere && delivered?.id) {
        await prisma.ticket.update({
          where: { id: ticketHere.id },
          data: {
            deliveryMessageId: delivered.id,
            staffId: interaction.user.id,
            screenshotVerified: true,
            ...(ticketHere.claimedAt ? {} : { claimedAt: new Date() }),
            status: 'CLAIMED'
          }
        }).catch(e => console.error('[TokenGen-Cmd] ticket update failed:', e));
        const tTimer = pendingVerificationTimers.get(interaction.channelId);
        if (tTimer) { clearTimeout(tTimer); pendingVerificationTimers.delete(interaction.channelId); }
        await delivered.react?.('❤️').catch(() => {});
      }
      if (interaction.guild) {
        await logAction(interaction.guild, '🛠️ /tokengen Delivered',
          `Staff ${interaction.user} generated a token via **/tokengen** for **${game.name}** (AppID \`${game.appId}\`, ${zipMB.toFixed(1)} MB).\n` +
          `**Stock Deducted:** \`${deduct ? 'YES' : 'NO'}\`\n` +
          `**In ticket channel:** ${ticketHere ? `<#${interaction.channelId}>` : 'no — posted in a regular channel'}\n` +
          `**Link:** ${persistent ? '🔓 **Persistent** (never expires, installer re-runnable)' : '⏱️ Single-use (expires + consumed on first install)'}`,
          0x57F287);
      }
      await logTenant(interaction.guildId, '📦 Token Delivered', `A token for **${game.name}** was delivered to <@${ticketHere?.userId || interaction.user.id}>.`, 0x57F287);
    } catch (sendErr) {
      const se = sendErr as Error;
      console.error('[TokenGen-Cmd] Delivery failed:', se);
      await interaction.editReply({ embeds: [
        new EmbedBuilder()
          .setTitle('⚠️ Token Built But Failed to Send')
          .setDescription(`Token generation succeeded but delivery failed:\n\`\`\`\n${(se?.message || String(se)).slice(0, 400)}\n\`\`\``)
          .setColor(0xED4245)
      ] }).catch(() => {});
    } finally {
      try { fsMod.unlinkSync(zipPath); } catch {}
    }
  } catch (err) {
    const e = err as Error;
    console.error('[TokenGen-Cmd] Error:', e);
    await interaction.editReply({ content: `❌ **/tokengen Error:** ${e.message}` });
  }
}
